"""create_initial_tables

Revision ID: 993bb6387087
Revises: 
Create Date: 2025-05-10 12:20:32.679767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993bb6387087'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avg_height', sa.Float(), nullable=True),
    sa.Column('avg_spread', sa.Float(), nullable=True),
    sa.Column('rotation_family', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_type_common_name'), ['common_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_plant_type_rotation_family'), ['rotation_family'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('preferred_units', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('garden_bed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('shape_params', sa.JSON(), nullable=False),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('unit_measure', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_layout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('layout_json', sa.Text(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('planting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('plant_type_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('date_planted', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['bed_id'], ['garden_bed.id'], ),
    sa.ForeignKeyConstraint(['plant_type_id'], ['plant_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planting_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_planting_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planting_year'))
        batch_op.drop_index(batch_op.f('ix_planting_is_current'))

    op.drop_table('planting')
    op.drop_table('garden_layout')
    op.drop_table('garden_bed')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('plant_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_type_rotation_family'))
        batch_op.drop_index(batch_op.f('ix_plant_type_common_name'))

    op.drop_table('plant_type')
    # ### end Alembic commands ###
