"""Add orientation to GardenBed

Revision ID: 1b55dcb40575
Revises: d048e9d6b562
Create Date: 2025-04-19 20:06:38.919470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b55dcb40575'
down_revision = 'd048e9d6b562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden_bed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orientation', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden_bed', schema=None) as batch_op:
        batch_op.drop_column('orientation')

    # ### end Alembic commands ###
