"""Add notes and last_modified to GardenBed

Revision ID: 22fbcceadbee
Revises: dfea7c16a626
Create Date: 2025-04-03 19:22:21.942919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fbcceadbee'
down_revision = 'dfea7c16a626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden_bed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
        batch_op.alter_column('length',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('width',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('unit_measure',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden_bed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.alter_column('unit_measure',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('width',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('length',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('last_modified')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
