"""feat(layout): add GardenLayout model for user yard and bed layout persistence

Revision ID: 652f312db7af
Revises: 1b55dcb40575
Create Date: 2025-04-24 19:39:54.315272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652f312db7af'
down_revision = '1b55dcb40575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garden_layout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('layout_json', sa.Text(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('garden_layout')
    # ### end Alembic commands ###
