"""Add x and y to GardenBed

Revision ID: d048e9d6b562
Revises: b43e5939226f
Create Date: 2025-04-19 09:09:24.198233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd048e9d6b562'
down_revision = 'b43e5939226f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden_bed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('y', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garden_bed', schema=None) as batch_op:
        batch_op.drop_column('y')
        batch_op.drop_column('x')

    # ### end Alembic commands ###
